Json support
dsx-tech/rhea pull request #2
Opened 2020-03-13 13:21 UTC by FemiLame

2020-03-13 13:39 UTC, pltanton commented on src/main/kotlin/uk/dsx/reactiveconfig/PropertyTypes.kt
> +data class NullNode(val value: Any?) : Node()
Зачем тут нужно вообще value null он и в африке null

2020-03-13 13:49 UTC, pltanton commented on src/main/kotlin/uk/dsx/reactiveconfig/PropertyTypes.kt
> +class PropertyTypeBase(val configManager: ConfigManager) {
Кажется это должно быть отвязано от конфиг менеджера

2020-03-13 13:57 UTC, pltanton commented on src/main/kotlin/uk/dsx/reactiveconfig/configsources/JsonConfigSource.kt
> +    private var channel: Channel<RawProperty>? = null
Не нужно налабл делать, если очно хочется чтобы в свежем объекте было не проиниченное значение можно использовать lateinit

2020-03-13 14:01 UTC, pltanton commented on src/main/kotlin/uk/dsx/reactiveconfig/configsources/JsonConfigSource.kt
> +                if (obj.toString() == "null") NullNode(null)
Это странно, нужно проверить на простм несте что клаксон выдает на нал

2020-03-13 14:03 UTC, pltanton requested changes
Нужно проавит мелочи и сделать PropertyType не связанным с конфиг менеджером

2020-03-20 15:14 UTC, pltanton commented on src/main/kotlin/uk/dsx/reactiveconfig/PropertyTypes.kt
> +class Failure<T> : ParseResult<T>()
Лучше Sucess и Failure сделать внутренними классами ParseResult, слишком уж популярное название, в будущем может быть коллизия в именах и путаница. Либо переименовать их в ParseSuccess ParseFailure или типа того

2020-03-20 15:14 UTC, pltanton commented on src/main/kotlin/uk/dsx/reactiveconfig/PropertyTypes.kt
> +    val map: ConcurrentHashMap<String, Reloadable<*>>,
Зачем тут Concurrent? Почему не хватит простой?

2020-03-20 15:14 UTC, pltanton commented on src/main/kotlin/uk/dsx/reactiveconfig/PropertyTypes.kt
> +    inner class PropertyType<T>(var initial: T, var parse: (Node?) -> ParseResult<T?>) {
Почему inner, а не просто nested класс оставить?

2020-03-22 18:10 UTC, FemiLame commented on src/main/kotlin/uk/dsx/reactiveconfig/PropertyTypes.kt
> +    inner class PropertyType<T>(var initial: T, var parse: (Node?) -> ParseResult<T?>) {
"A nested class marked as inner can access the members of its outer class". 
Нам ведь нужен доступ к переменным внешнего класса (map, flow, scope)

2020-03-23 08:38 UTC, pltanton approved these changes

2020-03-23 08:38 UTC, merged